---
title: "RWorksheet_Pabriaga#3a"
author: "John Martin S. Pabriaga"
date: "2024-09-30"
output: pdf_document
---
#USING VECTORS
# 1.a
first_11_letters <- LETTERS[1:11]
first_11_letters

# 1.b
odd_letters <- LETTERS[seq(1, length(LETTERS), by = 2)]
odd_letters

# 1.c
vowels <- LETTERS[LETTERS %in% c("A", "E", "I", "O", "U")]
vowels

# 1.d
last_5_lowercase <- letters[(length(letters)-4):length(letters)]
last_5_lowercase

# 1.e
subset_lowercase <- letters[15:24]
subset_lowercase

# 2.a
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

# 2.b
temp <- c(42, 39, 34, 34, 30, 27)
temp

# 2.c 
city_temp_df <- data.frame(city, temp)
city_temp_df

# 2.d
names(city_temp_df) <- c("City", "Temperature")
city_temp_df

# 2.e
str(city_temp_df)

# 2.f
city_temp_df[3:4,]

# 2.g
city_temp_df[which.max(city_temp_df$Temperature), "City"] 
city_temp_df[which.min(city_temp_df$Temperature), "City"]

#USING MATRICES
# 1
matrix(c(5,6,7,4,3,2,1,2,3,7,8,9), nrow = 2)

matrix(data = c(3,4,5,6,7,8), nrow = 3, ncol = 2)

diag(1, nrow = 6, ncol = 5)

diag(6)

# 2.a
matrix_data <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
matrix_data

# 2.b
matrix_multiplied <- matrix_data * 2
matrix_multiplied

# 2.c
matrix_data[2, ]

# 2.d
matrix_data[1:2, 3:4]

# 2.e
matrix_data[3, 2:3]

# 2.f 
matrix_data[, 4]

# 2.g
rownames(matrix_multiplied) <- c("isa", "dalawa", "tatlo")
colnames(matrix_multiplied) <- c("uno", "dos", "tres", "quatro")
matrix_multiplied

# 2.h
dim(matrix_data) <- c(6, 2)
matrix_data

#USING ARRAY
# 1 
array_dta <- array(c(1:24), c(3, 4, 2))
array_dta

dim(array_dta)

length(array_dta)

# 2
vectorA <- c(1:24)

an_Array <- array(vectorA, dim = c(3, 4, 2))
an_Array

# 3.a
values <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), times = 2)

array_data <- array(values, dim = c(2, 4, 3))
array_data

# 3.b
dim(array_data)


# 3.c
dimnames(array_data) <- list(c("a", "b"), c("A", "B", "C", "D"), c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))

array_data










